"""
Roofline dashboard — assembles all panels into results/roofline_dashboard.html.

Panels:
  1 — Roofline scatter: PyTorch ref / Triton / C++/CUDA + compiler overlay
  2 — Three-way SwiGLU benchmark table (latency, tflops, bandwidth)
  3 — Systolic array PE activity heatmap (Slice 24)
  4 — FSDP scaling curves + allocator time-series (Slice 24)
  5 — Inference Pareto + allocator hit rate comparison (Slice 24)

This module delivers Panels 1–2. Panels 3–5 are stubs filled by Slice 24.

dry_run=True: uses synthetic stub data for all panels.
             Writes to results_dir/roofline_dashboard.html.
"""
import json
from pathlib import Path

from profiler.roofline import build_panel1_html, _load_benchmark_data, _SYNTHETIC_BENCHMARK


# ---------------------------------------------------------------------------
# Panel 2 — Three-way SwiGLU benchmark table
# ---------------------------------------------------------------------------

def build_panel2_html(
    benchmark_data=None,
    dry_run: bool = False,
) -> str:
    """
    Generate Panel 2: three-way SwiGLU benchmark table as an HTML fragment.

    Columns: kernel, N, latency_ms, tflops, bandwidth_gb_s, % of peak.
    """
    data = _load_benchmark_data(benchmark_data, dry_run)

    rows = []
    for d in data:
        N    = d["config"].get("N", "?")
        name = d["kernel"]
        rows.append(
            f"<tr>"
            f"<td><b>{name}</b></td>"
            f"<td>{N}</td>"
            f"<td>{d['latency_ms']:.3f}</td>"
            f"<td>{d['tflops']:.2f}</td>"
            f"<td>{d['bandwidth_gb_s']:.1f}</td>"
            f"<td>{d.get('pct_of_peak', 0)*100:.1f}%</td>"
            f"</tr>"
        )

    return f"""
<div id="panel2" style="margin-bottom:40px">
  <h3>Panel 2 — Three-way SwiGLU Benchmark (PyTorch ref / Triton / CUDA)</h3>
  <table border="1" style="border-collapse:collapse">
    <tr>
      <th>Kernel</th><th>N</th>
      <th>Latency (ms)</th><th>TFLOPS</th>
      <th>Bandwidth (GB/s)</th><th>% of Peak</th>
    </tr>
    {''.join(rows)}
  </table>
  <p><em>Triton vs C++/CUDA gap target: &lt;15%. Both beat PyTorch ref.</em></p>
</div>
"""


# ---------------------------------------------------------------------------
# Stub panels for Slice 24
# ---------------------------------------------------------------------------

def _panel3_stub() -> str:
    return '<div id="panel3"><h3>Panel 3 — Systolic Array PE Heatmap (Slice 24)</h3><p><em>Coming in Slice 24.</em></p></div>'


def _panel4_stub() -> str:
    return '<div id="panel4"><h3>Panel 4 — FSDP Scaling + Allocator Time-Series (Slice 24)</h3><p><em>Coming in Slice 24.</em></p></div>'


def _panel5_stub() -> str:
    return '<div id="panel5"><h3>Panel 5 — Inference Pareto + Allocator Comparison (Slice 24)</h3><p><em>Coming in Slice 24.</em></p></div>'


# ---------------------------------------------------------------------------
# Dashboard assembler
# ---------------------------------------------------------------------------

def build_dashboard(
    results_dir=None,
    hw_name: str = "rtx_3090",
    dry_run: bool = False,
) -> str:
    """
    Assemble all panels into a single HTML file.

    results_dir: directory to write roofline_dashboard.html into.
                 Defaults to <repo-root>/results/.
    Returns the path of the written HTML file.
    """
    if results_dir is None:
        results_dir = Path(__file__).parent.parent / "results"
    results_dir = Path(results_dir)
    results_dir.mkdir(parents=True, exist_ok=True)

    # Load benchmark data once
    benchmark_json_path = results_dir / "swiglu_benchmark.json"
    benchmark_data = None
    if not dry_run and benchmark_json_path.exists():
        benchmark_data = json.loads(benchmark_json_path.read_text())

    panel1 = build_panel1_html(hw_name=hw_name, benchmark_data=benchmark_data, dry_run=dry_run)
    panel2 = build_panel2_html(benchmark_data=benchmark_data, dry_run=dry_run)
    panel3 = _panel3_stub()
    panel4 = _panel4_stub()
    panel5 = _panel5_stub()

    html = f"""<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>AxonForge Roofline Dashboard</title>
  <script src="https://cdn.jsdelivr.net/npm/chart.js@4"></script>
  <style>
    body {{ font-family: sans-serif; padding: 20px; max-width: 1100px; margin: auto; }}
    h2   {{ border-bottom: 2px solid #333; padding-bottom: 6px; }}
    table{{ margin-bottom: 10px; }}
    td, th {{ padding: 4px 10px; }}
  </style>
</head>
<body>
  <h2>AxonForge — Roofline &amp; Performance Dashboard</h2>
  <p>Hardware: <b>{hw_name}</b> | Mode: {'dry-run (synthetic data)' if dry_run else 'live'}</p>

  {panel1}
  {panel2}
  {panel3}
  {panel4}
  {panel5}

  <hr>
  <p><em>Generated by AxonForge profiler/dashboard.py</em></p>
</body>
</html>"""

    out_path = results_dir / "roofline_dashboard.html"
    out_path.write_text(html)
    return str(out_path)
