"""
Latency vs throughput Pareto plot for inference benchmarks.

Generates Panel 5 for the roofline dashboard.
The "knee" is the batch size beyond which throughput gains flatten while
latency grows — the optimal operating point for an inference server.

dry_run=True: generates a minimal HTML without running benchmarks.
"""
import json
import math
from pathlib import Path


def find_knee(results: list[dict]) -> dict | None:
    """
    Find the knee point: batch size where marginal throughput gain
    drops below 10% while latency more than doubles vs batch=1.
    Returns the knee result dict, or the highest-throughput entry if none found.
    """
    if not results:
        return None
    sorted_r = sorted(results, key=lambda r: r["batch_size"])
    if len(sorted_r) == 1:
        return sorted_r[0]

    baseline_latency = sorted_r[0]["latency_p50_ms"]
    prev_throughput = sorted_r[0]["throughput_tokens_s"]

    for r in sorted_r[1:]:
        marginal_gain = (r["throughput_tokens_s"] - prev_throughput) / max(prev_throughput, 1e-9)
        latency_ratio = r["latency_p50_ms"] / max(baseline_latency, 1e-9)
        if marginal_gain < 0.1 and latency_ratio > 2.0:
            return r
        prev_throughput = r["throughput_tokens_s"]

    # No knee found — return highest throughput
    return max(sorted_r, key=lambda r: r["throughput_tokens_s"])


def build_pareto_html(results: list[dict], output_path: str | Path) -> Path:
    """
    Render a latency vs throughput Pareto scatter plot to HTML.

    Points are colored by batch_size. The knee is marked with a star.
    Saves to output_path and returns the path.
    """
    output_path = Path(output_path)

    if not results:
        output_path.write_text("<html><body>No results to plot.</body></html>")
        return output_path

    knee = find_knee(results)
    knee_bs = knee["batch_size"] if knee else None

    # Build minimal inline HTML + Chart.js scatter
    points = []
    for r in results:
        if not (math.isfinite(r["latency_p50_ms"]) and math.isfinite(r["throughput_tokens_s"])):
            continue
        marker = "⭐" if r["batch_size"] == knee_bs else ""
        points.append({
            "x": round(r["latency_p50_ms"], 3),
            "y": round(r["throughput_tokens_s"], 1),
            "label": f"bs={r['batch_size']} sl={r['seq_len']}{marker}",
        })

    points_json = json.dumps(points)
    knee_json = json.dumps({
        "x": round(knee["latency_p50_ms"], 3),
        "y": round(knee["throughput_tokens_s"], 1),
    } if knee else {})

    html = f"""<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Inference Pareto Curve — AxonForge</title>
  <script src="https://cdn.jsdelivr.net/npm/chart.js@4"></script>
  <style>body{{font-family:sans-serif;padding:20px}} canvas{{max-width:900px}}</style>
</head>
<body>
  <h2>Inference Latency vs Throughput Pareto</h2>
  <p>Each point = (batch_size, seq_len). ⭐ = knee (optimal operating point).</p>
  <canvas id="chart"></canvas>
  <script>
    const pts = {points_json};
    const knee = {knee_json};
    const ctx = document.getElementById('chart').getContext('2d');
    new Chart(ctx, {{
      type: 'scatter',
      data: {{
        datasets: [{{
          label: 'Inference configs',
          data: pts.map(p => ({{x: p.x, y: p.y}})),
          backgroundColor: pts.map((p, i) => `hsl(${{i * 360 / pts.length}}, 70%, 50%)`),
          pointRadius: 6,
        }}]
      }},
      options: {{
        plugins: {{
          tooltip: {{
            callbacks: {{
              label: (ctx) => pts[ctx.dataIndex].label
            }}
          }}
        }},
        scales: {{
          x: {{title: {{display: true, text: 'p50 Latency (ms)'}}}},
          y: {{title: {{display: true, text: 'Throughput (tokens/s)'}}}}
        }}
      }}
    }});
  </script>
  <p><strong>Knee point:</strong> batch_size={knee_bs if knee_bs else 'N/A'}</p>
  <p><em>Generated by AxonForge serve/pareto.py</em></p>
</body>
</html>"""

    output_path.write_text(html)
    return output_path
